version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: ../_docker/app/Dockerfile
    container_name: task-pulse_backend_app
    volumes:
      - ./backend:/var/www
    user: "1000:33"
    command: >
      /bin/bash -c "composer install --no-interaction --optimize-autoloader && php-fpm"
    depends_on:
      - mysql
    networks:
      - task-pulse-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - HOST=0.0.0.0
    container_name: task-pulse_frontend_app
    networks:
      - task-pulse-network

  nginx:
    image: nginx:alpine
    container_name: task-pulse_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - task-pulse-network

  mysql:
    image: mysql:8.0
    container_name: task-pulse_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-pulse-network
  redis:
    image: redis:7-alpine
    container_name: task-pulse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task-pulse-network

volumes:
  mysql_data:
  redis_data:

networks:
  task-pulse-network:
    driver: bridge