version: "3.8"

services:
  app:
    build:
      context: ./fullstack-todo-backend
      dockerfile: ../_docker/app/Dockerfile
    container_name: fullstack_app
    volumes:
      - ./fullstack-todo-backend:/var/www
    user: "1000:33"
    depends_on:
      - mysql
    networks:
      - fullstack-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./fullstack-todo-frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - HOST=0.0.0.0
    networks:
      - fullstack-network

  nginx:
    image: nginx:alpine
    container_name: fullstack_nginx
    ports:
      - "8080:80"
    volumes:
      - ./fullstack-todo-backend:/var/www
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fullstack-network

  mysql:
    image: mysql:8.0
    container_name: fullstack_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullstack-network

volumes:
  mysql_data:

networks:
  fullstack-network:
    driver: bridge
